### ISSUE TITLE
microsocks enable no auth

### ISSUE THREAD

**Issue by currowth** [binhex/arch-privoxyvpn#10]
Can you enable no auth if  SOCKS_USER and  SOCKS_PASS variables are not passed or empty? This is useful for browsers like firefox that does not have the options for auth. I was able to get it working by modifying microsocks.sh and removing -u and -p param.

**Comment by Muppetteer** [comment]
Code looks better than mine. It's what I would have done if my bash scripting skills weren't almost non-existent.

I pulled the 'test' tagged image and it works fine. Thanks.
