### ISSUE TITLE
Having issues resolving name

### ISSUE THREAD

**Issue by brandoniffert** [binhex/arch-privoxyvpn#22]
Over the past few days I've noticed that my working privoxyvpn setup using Mullvad + wireguard has been having issues where it will "drop out" every so often. Turning debug on, I see this:

```
2021-12-28 17:03:14,374 DEBG 'watchdog-script' stdout output:
[debug] Checking we can resolve name 'www.google.com' to address...

2021-12-28 17:03:29,391 DEBG 'watchdog-script' stdout output:
[debug] Having issues resolving name 'www.google.com'
[debug] Retrying in 5 secs...
[debug] 11 retries left

2021-12-28 17:03:34,443 DEBG 'watchdog-script' stdout output:
[debug] DNS operational, we can resolve name 'www.google.com' to address '142.250.113.104 142.250.113.103 142.250.113.99 142.250.113.106 142.250.113.105 142.250.113.147'
[debug] Waiting for iptables chain policies to be in place...

2021-12-28 17:03:34,447 DEBG 'watchdog-script' stdout output:
[debug] iptables chain policies are in place
```

I'm using the same working docker-compose config from the README which was previously working and have tried numerous different Mullvad servers and it's always the same issue.

I can provided more troubleshooting info if told what to look for.

**Comment by Rascalov** [comment]
Did you eventually solve this issue somehow?
I get the same error even though nslookup in the container is functional.

**Comment by brandoniffert** [comment]
No, couldn't figure out the underlying problem and switched to a separate wireguard container and eventually gluetun.

**Comment by Rascalov** [comment]
Yesterday I discovered that my container missed the `ldns` package and opened an [issue](https://github.com/binhex/arch-privoxyvpn/issues/35) about it. On the [forum](https://forums.unraid.net/topic/78028-support-binhex-privoxyvpn/?do=findComment&comment=1424322) binhex responded.  Not sure if it will solve your issue though, since the debug info says that it did resolve the dns at one point.
