### ISSUE TITLE
Latest version crashes with error below

### ISSUE THREAD

**Issue by RacerBas** [binhex/arch-privoxyvpn#27]
"iptables v1.8.8 (legacy): can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
2023-02-18 13:35:12.854832 [crit] iptables kernel module 'ip_tables' not available, exiting script...
"

**Comment by binhex** [comment]
What does your docker run or compose file look like?

**Comment by RacerBas** [comment]
image: binhex/arch-privoxyvpn
    container_name: vpn
    devices:
      - /dev/net/tun
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./vpn/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=REDACTED
      - VPN_PASS=REDACTED
      - VPN_PROV=custom
      - VPN_INPUT_PORTS=8118,9118
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - SOCKS_USER=socksuser
      - SOCKS_PASS=REDACTED
      - ENABLE_SOCKS=yes
      - ENABLE_PRIVOXY=yes
      - DEBUG=false
      - UMASK=775
      - PUID=1000
      - PGID=1000
    ports:
      - "8118:8118"
      - "9118:9118"
    restart: unless-stopped

**Comment by binhex** [comment]
you are missing `--cap-add=NET_ADMIN` see readme examples:- https://github.com/binhex/arch-privoxyvpn not sure what the format is for docker compose

**Comment by RacerBas** [comment]
Ah that fixed it, I think I disabled it for a different issue some years ago in an older version.
Thanks!
