### ISSUE TITLE
Use proxy from other containers

### ISSUE THREAD

**Issue by gurabli** [binhex/arch-privoxyvpn#3]
What I would like to achieve, is to have all my traffic (including dns) to be routed over this VPNProxy container.
So there is container TEST. It should have all the traffic routed over the VPN by connecting to it with env variable http_proxy. And the TEST container should not have access directly to internet, so if the proxy is down, the TEST container will not have access to internet at all. Is this approach correct or am I missing something?
I guess if the  VPN connectin is down in your container than no internet connectin is allowed? 
Is DNS also routed over proxy?

I don't really like the link container approach as it gives problems of other kind, would be nice to have sorted this out this way.

**Comment by binhex** [comment]
this is currently not possible, if you want to literally all your traffic routed over vpn then your best bet is to create the tunnel on your home router.
