### ISSUE TITLE
[PIA] Port forwarding

### ISSUE THREAD

**Issue by Davy1992** [binhex/arch-privoxyvpn#4]
Hi,

First I'd like to thank you for creating such an awesome script, you saved me and so many other people days of research and work.

I was wondering if you could enable **port forwarding** for pia in [arch-privoxyvpn](https://github.com/binhex/arch-privoxyvpn). I saw that the `getvpnport.sh` script is included with the image but for whatever reason it isn't working.

I tried running it with these environment variables:
```
- VPN_PROV=pia
- APPLICATION=qbittorrent
- STRICT_PORT_FORWARD=yes
```
But I keep getting the _"Application does not require port forwarding or VPN provider is != pia"_ message.

Although when I run `docker exec privoxyvpn /root/getvpnport.sh` the port gets successfully assigned.

**Comment by binhex** [comment]
you dont need port forwarding for privoxy/socks5 to operate, and thus its not enabled, do you need incoming ports?

**Comment by Davy1992** [comment]
I do need incoming ports for a different service that I'm using in conjunction with your image via network_mode. I tried using `VPN_OPTIONS` with `--up` and `--route-up` to execute my own script but neither wanted to work.

The `--up` command would override the existing script and `--route-up` seems like it's being executed before I get DNS resolution, and when I add `--route-delay` I get `Having issues resolving name 'www.google.com'` for the duration of the delay that I set.

Could you at least point me in the right direction?
Should I focus on trying to get the `VPN_OPTIONS` working or the `/root/getvpnport.sh`

Thanks!
