### ISSUE TITLE
Support for arm64v8

### ISSUE THREAD

**Issue by afonsoc12** [binhex/arch-privoxyvpn#7]
Hello,

I have been an intensive user of your containers and congrats for your products.

However, I have recently made a torrent box with a raspberry pi for when I am on the go, and the container that I most use, privoxyvpn, does not work on an ARM system.

So I was wondering if you have planned to build ARM images for these containers too, since you already have a base arm image (arch-base-aarch64).

I believe that it would be greatly appreciated by the community, since there are a lot of RPi users.

Thanks!

**Comment by brandoniffert** [comment]
Would also like to know if there are any plans to support arm64v8 in the future.

**Comment by binhex** [comment]
OK it's been a long time coming, but it's here, the latest image now includes arm64 support, please pull it down and let me know how you get on.

**Comment by afonsoc12** [comment]
Great stuff, thank you for this addition!
I'll close the isue
